# Generated by Django 5.2.6 on 2025-09-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='J.K. Rowling', max_length=255),
            preserve_default=False,
        ),
    ]
